const test=require('node:test');
const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const app=require('../server/index');
const pool=require('../server/db');

test('favorites, rejection/expiry, daily reports, and secure password recovery',async()=>{
  const server=app.listen(0), base='http://127.0.0.1:'+server.address().port+'/api';
  const marker=Date.now()+'-'+crypto.randomBytes(3).toString('hex');
  const users=[],listingIds=[],password='InitialPassword123!';
  const oldSender=app.locals.passwordResetSender, deliveries=[];
  async function call(route,method='GET',body,token) {
    const response=await fetch(base+route,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{})});
    return {status:response.status,body:response.headers.get('content-type').includes('application/json')?await response.json():await response.text()};
  }
  try {
    for(const role of ['customer','business','customer','business']) {
      const email='experience-'+users.length+'-'+marker+'@plateup.test';
      const signup=await call('/auth/signup','POST',{name:'Experience test',email,password,role});
      assert.equal(signup.status,201);users.push({...signup.body.user});
      const login=await call('/auth/login','POST',{email,password,role});
      users.at(-1).token=login.body.token;
      assert.equal((await call('/me','PUT',{name:'Test '+role,city:'Dhaka'},login.body.token)).status,200);
    }
    const [customer,business,other,otherBusiness]=users;
    const listing=await call('/listings','POST',{title:'Experience meal',category:'Bakery',original_price:200,rescue_price:100,offer_start_time:'00:00',offer_end_time:'00:00'},business.token);
    assert.equal(listing.status,201);const id=listing.body.listing.id;listingIds.push(id);
    await call('/listings/'+id+'/today','PUT',{initial_quantity:10},business.token);
    const inventory=(await pool.query('SELECT id,offer_date::text FROM daily_availability WHERE listing_id=$1',[id])).rows[0];
    assert.equal((await call('/favorites')).status,401);
    assert.equal((await call('/favorites','GET',null,business.token)).status,403);
    assert.equal((await call('/favorites/listing/'+id,'PUT',{},customer.token)).status,200);
    assert.equal((await call('/favorites/listing/'+id,'PUT',{},customer.token)).status,200);
    assert.equal((await call('/favorites/business/'+business.id,'PUT',{},customer.token)).status,200);
    assert.equal((await call('/favorites','GET',null,customer.token)).body.saved.length,2);
    assert.equal((await call('/favorites','GET',null,other.token)).body.saved.length,0);
    await call('/favorites/listing/'+id,'DELETE',{},other.token);
    assert.equal((await call('/favorites','GET',null,customer.token)).body.listings.length,1);
    await call('/me','PUT',{name:'Experience test',city:'Khulna'},customer.token);
    const distant=await call('/favorites','GET',null,customer.token);
    assert.equal(distant.body.listings.length,0);assert.equal(distant.body.saved.length,2);
    assert.equal((await call('/favorites/listing/'+id,'PUT',{},customer.token)).status,404);
    await call('/me','PUT',{name:'Experience test',city:'Dhaka'},customer.token);
    const place=async quantity=>(await call('/orders','POST',{listing_id:id,quantity},customer.token)).body.orders[0];
    const rejected=await place(2);
    assert.ok(new Date(rejected.pickup_deadline)>new Date());
    const quote=await call('/cart/quote','POST',{listing_id:id,quantity:1},customer.token);
    assert.equal(quote.body.items[0].pickup_deadline,rejected.pickup_deadline);
    await pool.query("UPDATE listings SET offer_end_time='23:59' WHERE id=$1",[id]);
    assert.equal((await call('/orders','GET',null,customer.token)).body.find(row=>row.id===rejected.id).pickup_deadline,rejected.pickup_deadline);
    await pool.query("UPDATE listings SET offer_end_time='00:00' WHERE id=$1",[id]);
    assert.equal((await call('/orders/'+rejected.id,'PATCH',{status:'rejected',reason:'Closed'},otherBusiness.token)).status,403);
    assert.equal((await call('/orders/'+rejected.id,'PATCH',{status:'rejected'},business.token)).status,400);
    assert.equal((await call('/orders/'+rejected.id,'PATCH',{status:'rejected',reason:'Kitchen equipment issue'},business.token)).status,200);
    assert.equal((await call('/orders/'+rejected.id,'PATCH',{status:'rejected',reason:'Again'},business.token)).status,400);
    assert.equal((await call('/orders','GET',null,customer.token)).body.find(row=>row.id===rejected.id).status_reason,'Kitchen equipment issue');
    const overdue=await place(3);
    await pool.query("UPDATE orders SET pickup_deadline=NOW()-INTERVAL '1 minute' WHERE id=$1",[overdue.id]);
    const tomorrow=(await pool.query('INSERT INTO daily_availability(listing_id,offer_date,initial_quantity,remaining_quantity) VALUES ($1,$2::date+1,4,4) RETURNING id',[id,inventory.offer_date])).rows[0];
    const parallel=await Promise.all([call('/orders','GET',null,customer.token),call('/orders','GET',null,business.token)]);
    for(const result of parallel) assert.equal(result.body.find(row=>row.id===overdue.id).status,'expired');
    const remaining=(await pool.query('SELECT id,remaining_quantity FROM daily_availability WHERE listing_id=$1',[id])).rows;
    assert.equal(remaining.find(row=>row.id===inventory.id).remaining_quantity,10);
    assert.equal(remaining.find(row=>row.id===tomorrow.id).remaining_quantity,4);
    assert.equal((await call('/orders/'+overdue.id,'PATCH',{status:'completed',pickup_code:overdue.pickup_code},business.token)).status,400);
    const customerOrders=(await call('/orders','GET',null,customer.token)).body;
    assert.equal(customerOrders.find(row=>row.id===overdue.id).pickup_code,undefined);
    const notes=(await call('/notifications','GET',null,customer.token)).body.notifications;
    assert.equal(notes.filter(row=>row.order_id===overdue.id&&row.event==='expired').length,1);
    const completed=await place(1);
    for(const status of ['confirmed','ready','completed']) assert.equal((await call('/orders/'+completed.id,'PATCH',{status,pickup_code:completed.pickup_code},business.token)).status,200);
    const route='/business/analytics/daily?from='+inventory.offer_date+'&to='+inventory.offer_date;
    const report=await call(route,'GET',null,business.token);
    assert.equal(report.status,200);
    assert.deepEqual(report.body.days[0],{date:inventory.offer_date,offered:10,reserved:0,collected:1,remaining:9,missed:3,revenue:'100.00'});
    assert.equal((await call(route,'GET',null,customer.token)).status,403);
    assert.equal((await call(route,'GET',null,otherBusiness.token)).body.days.length,0);
    assert.equal((await call('/business/analytics/daily?from=2026-02-30&to=2026-03-01','GET',null,business.token)).status,400);
    const csv=await call(route+'&format=csv','GET',null,business.token);
    assert.equal(csv.status,200);assert.match(csv.body,/date,offered,reserved,collected,remaining,missed,revenue/);
    assert.ok(csv.body.includes(inventory.offer_date+',10,0,1,9,3,100.00'));
    await call('/listings/'+id,'DELETE',{},business.token);
    assert.equal((await call('/favorites','GET',null,customer.token)).body.listings.length,0);
    await call('/favorites/listing/'+id,'DELETE',{},customer.token);
    assert.equal((await call('/favorites','GET',null,customer.token)).body.saved.length,1);

    app.locals.passwordResetSender=null;
    assert.equal((await call('/auth/forgot-password','POST',{email:customer.email})).status,503);
    app.locals.passwordResetSender=async delivery=>deliveries.push(delivery);
    const unknown=await call('/auth/forgot-password','POST',{email:'missing-'+marker+'@plateup.test'});
    const known=await call('/auth/forgot-password','POST',{email:customer.email});
    assert.equal(known.status,202);assert.deepEqual(known.body,unknown.body);assert.equal(known.body.token,undefined);
    assert.equal(deliveries.length,1);
    const raw=deliveries[0].token;
    const stored=(await pool.query('SELECT token_hash FROM password_resets WHERE user_id=$1',[customer.id])).rows[0];
    assert.notEqual(stored.token_hash,raw);assert.equal(stored.token_hash,crypto.createHash('sha256').update(raw).digest('hex'));
    await call('/auth/forgot-password','POST',{email:customer.email});assert.equal(deliveries.length,1,'Cooldown prevents repeated emails');
    assert.equal((await call('/auth/reset-password','POST',{token:'0'.repeat(64),new_password:'UpdatedPassword123!'})).status,400);
    assert.equal((await call('/auth/reset-password','POST',{token:raw,new_password:'UpdatedPassword123!'})).status,200);
    assert.equal((await call('/auth/reset-password','POST',{token:raw,new_password:'AnotherPassword123!'})).status,400);
    assert.equal((await call('/me','GET',null,customer.token)).status,401);
    assert.equal((await call('/auth/login','POST',{email:customer.email,password,role:'customer'})).status,401);
    const newLogin=await call('/auth/login','POST',{email:customer.email,password:'UpdatedPassword123!',role:'customer'});
    assert.equal(newLogin.status,200);
    assert.equal((await call('/auth/change-password','POST',{current_password:'wrong',new_password:'FinalPassword123!'},newLogin.body.token)).status,400);
    assert.equal((await call('/auth/change-password','POST',{current_password:'UpdatedPassword123!',new_password:'FinalPassword123!'},newLogin.body.token)).status,200);
    assert.equal((await call('/me','GET',null,newLogin.body.token)).status,401);
    await call('/auth/forgot-password','POST',{email:other.email});
    await pool.query("UPDATE password_resets SET expires_at=NOW()-INTERVAL '1 second' WHERE user_id=$1",[other.id]);
    assert.equal((await call('/auth/reset-password','POST',{token:deliveries.at(-1).token,new_password:'UpdatedPassword123!'})).status,400);
  } finally {
    app.locals.passwordResetSender=oldSender;
    const ids=users.map(user=>user.id);
    await pool.query('DELETE FROM sales_data WHERE business_id=ANY($1)',[ids]);
    await pool.query('DELETE FROM orders WHERE customer_id=ANY($1)',[ids]);
    await pool.query('DELETE FROM daily_availability WHERE listing_id=ANY($1)',[listingIds]);
    await pool.query('DELETE FROM listings WHERE id=ANY($1)',[listingIds]);
    await pool.query('DELETE FROM customers WHERE user_id=ANY($1)',[ids]);
    await pool.query('DELETE FROM businesses WHERE user_id=ANY($1)',[ids]);
    await pool.query('DELETE FROM users WHERE id=ANY($1)',[ids]);
    await new Promise(resolve=>server.close(resolve));
  }
});
